name: "Rmarkdown with navbar"                                
output_dir: "."
navbar:
  title: "Rmarkdown with navbar"                            
  type: inverse
  right:
    - text: "Contact me"
      icon: fa-envelope-o
      href: https://www.stackoverflow.com                  
    - text: "GitHub"
      icon: fa-github
      href: https://www.stackoverflow.com  
    - text: "Stackoverflow"
      icon: fa-stack-overflow
      href: https://www.stackoverflow.com  
    - text: "Youtube"
      icon: fa-youtube
      href: https://www.stackoverflow.com  
    - text: "Instagram"
      icon: fa-instagram
      href: https://www.stackoverflow.com  
    - text: "Twitter"
      icon: fa-twitter
      href: https://www.stackoverflow.com  
output:
  html_document:
    theme: spacelab
    highlight: textmate
