name: "Rmarkdown with navbar"                                
output_dir: "."
navbar:
  title: "Rmarkdown with navbar"                            
  type: inverse
  right:
    - text: "Contact me"
      icon: fa-envelope-o
      href: https://www.stackoverflow.com
theme: spacelab
